version: 1.3.0.{build}
branches:
  only:
  - 1.3
skip_tags: true
configuration: Release
platform: Any CPU
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(build_type)-$(APPVEYOR_REPO_COMMIT)'
environment:
  credentials_box_client_id:
    secure: 8MKxTOowo2fat6cNXGbFfvn6typiEtmCKsrptrWiEFUEoKlT1DUn40iGNcIELRA1
  credentials_box_client_secret:
    secure: hJhzDVJuGd/WMnoSXhosvOM/1PGcYlKbtQjA6xyrmnmZcqCTMzqIdA6JXlo/V2Br
  credentials_dropbox_consumer_key:
    secure: Da/6KY1cu9CUM3iOqSpcUw==
  credentials_dropbox_consumer_secret:
    secure: KkyKyUY+buT/MZagXDP4cw==
  credentials_flickr_consumer_key:
    secure: fY8s0OkOMYwCjSZoL/6yZcP8xeT6J2EJLjbUMI5lAW42S5QT2U2B41KrmeP2NpnQ
  credentials_flickr_consumer_secret:
    secure: 9TthlljPHXWPkDDeG3uiFVJ9YJwHZOV0ZsojaIBBuvw=
  credentials_imgur_consumer_key:
    secure: XRTg1Ecs6ER9m4779CJAng==
  credentials_imgur_consumer_secret:
    secure: gcCp/gJF8vqmnCUPKyb04H8Oz9mWmiB00U5X7iI/DGr5mxjoCG1khc6/zn6aSSqn
  credentials_photobucket_consumer_key:
    secure: oo9GD1Y8dkrli6hMfnnYsw==
  credentials_photobucket_consumer_secret:
    secure: GiNPoe9klM/YkoHIA/YHqOYrIaYwSFK7Ph9m8jT9uPP1l6+Hd5K8dVMw5DNa50oG
  credentials_picasa_consumer_key:
    secure: bjKXhFZkDqaq98XBrz5oQKQfT8CLpuv2ZAiBIwkzloaAPUs97b5yx6h/xFaE4NLS
  credentials_picasa_consumer_secret:
    secure: yNptTpmJWypbu9alOQtetxU66drr2FKxoPflNgRJdag=
  build_type: ALPHA
before_build:
  - nuget restore
  - ps: Build/before_build.ps1
build:
  project: greenshot.sln
  verbosity: normal
after_build:
- ps: Build/after_build.ps1
on_success:
- ps: Build/build_success.ps1
test: off
artifacts:
- path: AssemblyDir\Greenshot*INSTALLER*.exe
  name: Installer
- path: AssemblyDir\Greenshot*paf.exe
  name: Portable
- path: AssemblyDir\Greenshot-NO*.zip
  name: Zip
- path: Build\additional_files\readme.txt
  name: Readme
- path: AssemblyDir\Greenshot-DEBUGSYMBOLS*.zip
  name: DEBUGSYMBOLS
deploy:
- provider: GitHub
  tag: Greenshot-$(build_type)-$(APPVEYOR_BUILD_VERSION)
  description: 
  auth_token:
    secure: h0R+O/UoDM5Fy9XBfpRWLxFdR4a6CS+hDxr/MUeiRSviAmUsSlvsGSyOG6KiAVrL
  prerelease: true
  on:
    build_type: RELEASE_CANDIDATE
- provider: GitHub
  tag: Greenshot-$(build_type)-$(APPVEYOR_BUILD_VERSION)
  description: 
  auth_token:
    secure: h0R+O/UoDM5Fy9XBfpRWLxFdR4a6CS+hDxr/MUeiRSviAmUsSlvsGSyOG6KiAVrL
  prerelease: true
  on:
    build_type: BETA
- provider: GitHub
  tag: Greenshot-$(build_type)-$(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: h0R+O/UoDM5Fy9XBfpRWLxFdR4a6CS+hDxr/MUeiRSviAmUsSlvsGSyOG6KiAVrL
  on:
    build_type: RELEASE
notifications:
- provider: Email
  to:
  - robin@getgreenshot.org
  - jens@getgreenshot.org
  - thomas@getgreenshot.org
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true